### ISSUE TITLE
Installation/setup issues

### ISSUE THREAD

**Issue by krzysztof01-sz** [jakubkazimierczak/ct8_refresh#1]
Hi Jakub, I've encountered a problem with running your project on my computer. 
After creating a new folder and running first two commands, everything works well, but when I pasted below command:
```
pipx install git+https://github.com/jakubkazimierczak/ct8_refresh
```
there is an error:
```
'pipx' is not recognized as an internal or external command,
operable program or batch file.
```
What should I do?

**Comment by jakubkazimierczak** [comment]
If you have `pipx` on your system, please verify that it's available in PATH with this command:
```
python -m pipx ensurepath
```
If you don't have pipx, please install it according to [pipx docs](https://pipxproject.github.io/pipx/installation/) and try again.

**Comment by krzysztof01-sz** [comment]
Works well but I needed to restart my computer (Windows). Thank you!
